-keepattributes *Annotation*
-keep class * extends androidx.room.RoomDatabase { *; }
-keep class * extends androidx.lifecycle.ViewModel { *; }
-dontwarn kotlinx.coroutines.**
-dontwarn androidx.room.**
